VendorEditIcon = "((//div[contains(@class,'table_container_body')])[1]/div//span[text()='vendorName'])[1]//following::button[1]/*[local-name()='svg']"
AddRelationButton = "//button[text()='Add Relation']"
AlertIdInputField = "//input[@name='alertId']"
RelationNavigateBackButton = "//main[@id='main-content']//button"
RelationSearchBar = "//input[@name='search']"
VendorRelationDeleteIcon = "//div[text()='vendorRelation']//following::button[2]"
DeleteVendorRelationPopup = "//section//span[text()='DELETE RELATION']"
DeleteVendorRelationConfirmBtn = "//section//span[text()='DELETE RELATION']//following::button[text()='Delete']"
