# Rules page
AddRuleButton = "//button[text()='Add Rule']"
RulesPageSearchBar = "//input[@name='search']"
ActivateRuleToggleSwitch = "//span[text()='ruleName']//preceding::div[contains(@class,'dz_input-switch__container')][1]"
ViewRuleIcon = "//span[text()='ruleName']//following::button[2]"
EditRuleIcon = "//span[text()='ruleName']//following::button[3]"
DeleteRuleIcon = "//span[text()='ruleName']//following::button[4]"
DeleteRulePopupVerification = "//span[contains(text(),'Delete Rule')]//following::h4"
RuleDeleteConfirmButton = "//span[contains(text(),'Delete Rule')]//following::button[contains(text(),'Delete')]"
RuleTableActionMenuIcon = "//span[text()='ruleName']//following::button[1]"

# Rule view collapsable side menu elements
ViewRuleMenuMonitoringSystemsTabButton = "//button[@id='switch-tab-MONITORING_SYSTEMS']"
ViewRuleMenuRuleDetailsTabButton = "//button[@id='switch-tab-RULE_DETAILS']"
ViewRuleMenuMitreTechniquesTabButton = "//button[@id='switch-tab-MITRE_TECHNIQUES']"
ViewRuleMenuPlaybooksTabButton = "//button[@id='switch-tab-PLAYBOOKS']"
ViewRuleMenuCompaniesTabButton = "//button[@id='switch-tab-COMPANIES']"
RelationIdsInViewRuleMenu = "(//section//span[text()='ruleName'])[2]//following::span[text()='Relations'][2]//following::span"
ViewRuleMenuCrossIcon = "//div[contains(@class,'fixed w-screen h-screen')]/section/div/button/*[local-name()='svg']"
SelectVendorProfileButton_ViewRuleMenu = "(//span[text()='Rule Profile'])[2]//following::button[1]"

# Rules sub-module common elements
RuleId = "//main[@id='main-content']//h4"
NavigateBackToRulesPage = "(//section)[2]//button[contains(@class,'dz_button-common')]"
RuleDetailsSideMenuOption = "//button/span[text()='Rule Details']"
MitreTechniquesSideMenuOption = "//button/span[text()='Mitre Techniques']"
PlaybooksSideMenuOption = "//button/span[text()='Playbooks']"
MainSideMenuOption = "//button/span[text()='Main']"
CompaniesSideMenuOption = "//button/span[text()='Companies']"
GoToMonitoringLinkBtn = "//span[text()='Go to Monitoring Systems']"
GoToRuleDetailsLinkBtn = "//span[text()='Go to Rule Details']"
GoToMitreTechniquesLinkBtn = "//span[text()='Go to Mitre Techniques']"
GoToPlaybooksLinkBtn = "//span[text()='Go to Playbooks']"
GoToCompaniesLinkBtn = "//span[text()='Go to Companies']"

# Rules sub-module Main
LanguageDropdown = "//input[@id='language']"
RuleNameInputField = "//input[@name='ruleName']"
RuleAttackInputField = "//input[@name='ruleAttack']"
DataSourceDropdown = "//input[@id='dataSource']"
EventTypeDropdown = "//input[@id='eventType']"
MonitoringSystemDropdown = "//input[@id='integration']"
SearchRelationInputField = "//input[@name='search']"
RelationSearched = "//span[text()='Unselected']//following::div[2]"
DragRightArrowKey = "(//span[text()='Unselected']//following::div//button)[1]/*[local-name()='svg']"
DragLeftArrowKey = "(//span[text()='Unselected']//following::div//button)[2]"

# Rules sub-module Monitoring Systems
RuleDescriptionInputField = "//textarea[@id='documentationDescription']"
CvssCalculatorButton = "//span[text()='CVSS']//following::button[1]"
CvssCalculatorTab = "//section//h4[text()='CVSS Calculator']"
LocalAttackVendorType = "//h4[contains(text(),'CVSS')]//following::span[text()='Local (L)']"
HighAttackComplexity = "//h4[contains(text(),'CVSS')]//following::span[contains(text(),'Attack Complexity')]//following::span[text()='High (H)'][1]"
LowPrivilegesRequired = "//h4[contains(text(),'CVSS')]//following::span[contains(text(),'Privileges')]//following::span[text()='Low (L)'][1]"
HighConfidentiality = "//h4[contains(text(),'CVSS')]//following::span[contains(text(),'Confidentiality')]//following::span[text()='High (H)'][1]"
HighIntegrity = "//h4[contains(text(),'CVSS')]//following::span[contains(text(),'Integrity')]//following::span[text()='High (H)'][1]"
CvssCalculatorTabCrossIcon = "//section//h4[text()='CVSS Calculator']//following::button[1]"
AddRulesetButton = "//span[text()='Ruleset']//following::button[1]"
RuleSetGroupDropdown = "//span[contains(text(),'to Main')]//preceding::input[@id='group'][1]"
RulesetGroupValueInputField = "//span[contains(text(),'to Main')]//preceding::input[@id='value'][1]"
SelectedVendorProfile = "(//span[text()='Rule Profile'])[2]//following::span[text()='vendorProfileName']"
AddVendorProfileButton = "(//span[text()='Rule Profile'])[2]//following::button[1]"
SelectVendorProfileDropdown = "(//span[text()='Rule Profile'])[2]//following::button[4]"
VendorProfileNameInputField = "//span[contains(text(),'Add Vendor')]//following::input[@id='name']"
SaveNewVendorProfileButton = "//span[contains(text(),'Add Vendor')]//following::button[2]"
DeleteVendorProfileButton = "(//span[text()='Rule Profile'])[2]//following::span[text()='vendorProfile']//following::button[3]"

# Rules sub-module Incident Description
IncidentDescriptionInputField = "//textarea[@name='incidentDescription']"
GroupingSearchInputField = "//input[@name='search']"
GroupingLoadSpinner = "(//*[local-name()='svg' and contains(@class,'animate-spin')])[1]"

# Rules sub-module Mitre Techniques
MitreTechniquePageLoadSpinner = "(//*[local-name()='svg' and contains(@class,'animate-spin')])[1]"
MitreTechniqueSearchBar = "//input[@name='search']"

# Rules sub-module Playbooks
AddPlaybookButton = "//button[text()='Add Playbook']"
PlaybookSearchBar = "//input[@name='search']"
ActivatePlaybookToggleSwitch = "(//div[contains(@class,'table_container_body')])[1]//div[text()='playbookName']//preceding::input[contains(@class,'dz_input-switch')]"
EditPlaybookIcon = "(//div[contains(@class,'table_container_body')])[1]//div[contains(text(),'playbookName')]//following::button[1]"
DeletePlaybookIcon = "(//div[contains(@class,'table_container_body')])[1]//div[contains(text(),'playbookName')]//following::button[2]"
DeletePlaybookConfirmationPopup = "//span[contains(text(),'Playbook Delete')]//following::h4"
PlaybookDeleteConfirmButton = "//span[contains(text(),'Playbook Delete')]//following::button[contains(text(),'Delete')]"
PlaybookNameInputField = "//input[@name='playbookName']"
AdvancePlaybookVisibilityRadioOption = "//input[@id='playbookVisibilityPrivate']"
SelectCompanyDropdown = "//input[@id='playbookVisibilityAdvancedCompany']"
PlaybookPhaseType = "//span[text()='phaseName']//following::input[@id='type'][1]"
PlaybookPhaseStep = "//span[text()='phaseName']//following::textarea[@id='description'][1]"
AddPreparationStepButton = "//button[text()='Add preparation Step']"
AddIdentificationStepButton = "//button[text()='Add identification Step']"
AddContainmentStepButton = "//button[text()='Add containment Step']"
AddEradicationStepButton = "//button[text()='Add eradication Step']"
AddRecoveryStepButton = "//button[text()='Add recovery Step']"
LessonsLearnedInputField = "//span[text()='Lessons Learned']//following::textarea[@name='lessonLearned']"
AddLessonsLearnedButton = "//button[text()='Add lesson learned Step']"
CommentsInputField = "//span[text()='Comments']//following::textarea[@name='comment']"
AddCommentButton = "//button[text()='Add comment']"
VersioningReviewInputField = "//span[text()='Versioning']//following::textarea[@name='review']"
EditPhaseStepInputField = "(//span[text()='phaseName']//following::div[contains(@class,'input-text-area')]//textarea)[1]"
EditPhaseStepConfirmIcon = "(//span[text()='phaseName']//following::div[contains(@class,'input-text-area')]//textarea)[1]//following::button[1]"

# Rules sub-module Companies
CompanyToSelectForRule = "//span[text()='Companies']//following::span[text()='companyName']"
RuleProfileDropdown = "//span[text()='companyName']//following::input[@id='ruleProfile']"
MonitoringProfileDropdown = "//span[text()='companyName']//following::input[@id='vendorProfile']"
WhiteListDropdown = "//span[text()='companyName']//following::input[@id='whiteList']"
BlackListDropdown = "//span[text()='companyName']//following::input[@id='blackList']"
ActivateRuleInCompanyToggleSwitch = "//span[text()='companyName']//following::div[contains(@class,'dz_input-switch')][1]"
